name: Antonin Brun

# Short bio or description (displayed in the header)
# description: the profile of an engineer, researcher and software developer

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: images/headshot_crop.jpg

